AWSTemplateFormatVersion: '2010-09-09'
Description: Udagram Application Resources

Parameters:
  VPCId:
    Type: String
    Description: VPC ID
    Default: "YourDefaultVPCId"
  PublicSubnet1Id:
    Type: String
    Description: Public Subnet 1 ID
    Default: "YourDefaultPublicSubnet1Id"
  PublicSubnet2Id:
    Type: String
    Description: Public Subnet 2 ID
    Default: "YourDefaultPublicSubnet2Id"
  PrivateSubnet1Id:
    Type: String
    Description: Private Subnet 1 ID
    Default: "YourDefaultPrivateSubnet1Id"
  PrivateSubnet2Id:
    Type: String
    Description: Private Subnet 2 ID
    Default: "YourDefaultPrivateSubnet2Id"

Resources:
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Subnets:
        - !Ref PublicSubnet1Id
        - !Ref PublicSubnet2Id
      SecurityGroups:
        - !Ref LoadBalancerSecurityGroup

  LoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Load Balancer
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

Outputs:
  LoadBalancerDNS:
    Description: Load Balancer DNS Name
    Value: !GetAtt LoadBalancer.DNSName
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-LoadBalancerDNS"
